kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: dasmalwerk-collector
spec:
  schedule: "@daily"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: malware-mount
              persistentVolumeClaim:
                claimName: dasmalwerk-pvc
          containers:
            - name: dasmalwerk-collector
              image: gclef/dasmalwerk:1.1
              imagePullPolicy: "IfNotPresent"
              volumeMounts:
                - name: malware-mount
                  mountPath: /RAID
          imagePullSecrets:
            - name: registrycreds