kind: CronJob
apiVersion: batch/v1
metadata:
  name: dasmalwerk-collector
spec:
  schedule: "10 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: malware-mount
              persistentVolumeClaim:
                claimName: dasmalwerk-pvc
          containers:
            - name: dasmalwerk-collector
              image: gclef/dasmalwerk:1.3
              imagePullPolicy: "IfNotPresent"
              env:
                - name: ES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: malware-collection-secrets
                      key: ES_PASSWORD
                - name: ES_HOST
                  valueFrom:
                    secretKeyRef:
                      name: malware-collection-secrets
                      key: ES_HOST
                - name: ES_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: malware-collection-secrets
                      key: ES_USERNAME
                - name: DAS_MALWERK_PATH
                  value: "/RAID/malwerk/"
              volumeMounts:
                - name: malware-mount
                  mountPath: /RAID
          imagePullSecrets:
            - name: registrycreds