kind: CronJob
apiVersion: batch/v1
metadata:
  name: malwarebazaar-collector
spec:
  schedule: "30 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: malware-mount
              persistentVolumeClaim:
                claimName: mbazaar-pvc
          containers:
            - name: mbazaar-collector
              image: gclef/malwarebazaar:1.5
              imagePullPolicy: "IfNotPresent"
              env:
                - name: ES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: malware-collection-secrets
                      key: ES_PASSWORD
                - name: ES_HOST
                  valueFrom:
                    secretKeyRef:
                      name: malware-collection-secrets
                      key: ES_HOST
                - name: ES_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: malware-collection-secrets
                      key: ES_USERNAME
                - name: MBAZAAR_PATH
                  value: "/RAID/mbazaar/"
              volumeMounts:
                - name: malware-mount
                  mountPath: /RAID
          imagePullSecrets:
            - name: registrycreds