kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: malware-collector
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: malware-collector-job
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: malware
              nfs:
                server: 192.168.1.29
                path: /mnt/DroboFS/Shares/malware
          containers:
            - name: malware-collector
              image: gclef/malware:1.0
              imagePullPolicy: "IfNotPresent"
              volumeMounts:
                - name: malware
                  mountPath: /RAID
          imagePullSecrets:
            - name: registrycreds