apiVersion: v1
kind: Secret
metadata:
  name: malware-collection-secrets
type: Opaque
stringData:
    MALSHARE_API_KEY: ""
    VXUG_PATH: /RAID
    VXUG_TOKEN: ""
    # VXUG-specific token for the analysis site.
    URLHAUS_PATH: /RAID