kind: Job
apiVersion: batch/v1
metadata:
  name: vxug-collector-oneoff
spec:
  template:
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: malware-mount
          nfs:
            server: 192.168.1.29
            path: /mnt/DroboFS/Shares/malware/vxug
      containers:
        - name: vxug-collector
          image: gclef/malware:vxug-1.2
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: malware-mount
              mountPath: /RAID
      env:
        - name: CLEANUP
          value: "False"
        - name: ARCHIVE_PATH
          valueFrom:
            secretKeyRef:
              name: malware-collection-secrets
              key: VXUG_ARCHIVE_PATH
        - name: ANALYSIS_URL
          valueFrom:
            secretKeyRef:
              name: malware-collection-secrets
              key: ANALYSIS_URL
        - name: ANALYSIS_TOKEN
          valueFrom:
            secretKeyRef:
              name: malware-collection-secrets
              key: ARCHIVE_TOKEN
        - name: ARCHIVE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: malware-collection-secrets
              key: ARCHIVE_PASSWORD
        - name: VXUG_PATH
          valueFrom:
            secretKeyRef:
              name: malware-collection-secrets
              key: VXUG_PATH
      imagePullSecrets:
        - name: registrycreds