kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: vxug-collector
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: malware-mount
              nfs:
                server: 192.168.1.29
                path: /mnt/DroboFS/Shares/malware
          containers:
            - name: malware-collector
              image: gclef/malware:vxug-1.2
              imagePullPolicy: "IfNotPresent"
              volumeMounts:
                - name: malware-mount
                  mountPath: /RAID
          env:
            - name: CLEANUP
              value: "False"
          imagePullSecrets:
            - name: registrycreds