kind: CronJob
apiVersion: batch/v1
metadata:
  name: vxvault-collector
spec:
  schedule: "50 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: malware-mount
              persistentVolumeClaim:
                claimName: vxvault-pvc
          containers:
            - name: vxvault-collector
              image: gclef/vxvault:1.9
              imagePullPolicy: "IfNotPresent"
              env:
                - name: ES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: malware-collection-secrets
                      key: ES_PASSWORD
                - name: ES_HOST
                  valueFrom:
                    secretKeyRef:
                      name: malware-collection-secrets
                      key: ES_HOST
                - name: ES_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: malware-collection-secrets
                      key: ES_USERNAME
                - name: VXVAULT_PATH
                  value: "/RAID/vxvault/"
              volumeMounts:
                - name: malware-mount
                  mountPath: /RAID
          imagePullSecrets:
            - name: registrycreds