kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: vxvault-collector
spec:
  schedule: "@daily"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: malware-mount
              nfs:
                server: 192.168.1.29
                path: /mnt/DroboFS/Shares/malware
          containers:
            - name: vxvault-collector
              image: gclef/malware:vxvault-1.0
              imagePullPolicy: "IfNotPresent"
              volumeMounts:
                - name: malware-mount
                  mountPath: /RAID
          imagePullSecrets:
            - name: registrycreds