kind: CronJob
apiVersion: batch/v1
metadata:
  name: vxvault-collector
spec:
  schedule: "50 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: malware-mount
              persistentVolumeClaim:
                claimName: vxvault-pvc
          containers:
            - name: vxvault-collector
              image: gclef/vxvault:2.0
              imagePullPolicy: "IfNotPresent"
              env:
                - name: VXVAULT_PATH
                  value: "/RAID/vxvault/"
              volumeMounts:
                - name: malware-mount
                  mountPath: /RAID
          imagePullSecrets:
            - name: registrycreds